### ISSUE TITLE
Example or starter project

### ISSUE THREAD

**Issue by ozum** [hmsk/nuxt-ts#1]
Hi,

Thanks for the plugin. Is it possible to provide an example or starter project. I'm struggling to create nuxt 2 typescript project from scratch.

Kind Regards,

**Comment by hmsk** [comment]
Hi, @ozum 

This might help you, which is the starter template to use `nuxt-ts`.
https://github.com/hmsk/nuxt-typescript-edge-template
However, it's a bit stale (installs nuxt-edge 2.00) though.

Currently, I'm planning to release the next version of `nuxt-ts`. Then I may provide the sample project for the latest version 🤔

**Comment by ozum** [comment]
That would be great. Thanks.

**Comment by hmsk** [comment]
Using the latest `nuxt-ts`, I've updated the sample https://github.com/hmsk/nuxt-typescript-template
With vue-cli (runs older cli process though), you can get the simple ready-made Nuxt2 + TS 3 project.

Mentioned in e885168d7a3c1bde9b358ca3a9b0cc1bc6502007
