### ISSUE TITLE
How to import .ts files?

### ISSUE THREAD

**Issue by francoism90** [hmsk/nuxt-ts#4]
I must do something wrong and as a newbie I'm kinda lost, hope you can help. :)
I'm using express as server middleware.

```
tsconfig.json:
{
  "extends": "./node_modules/nuxt-ts/tsconfig.nuxt-ts.json"
}

api/index.ts:
const express = require('express')

// Create express instnace
const app = express()

const test = require('./routes/test')

// Export the server middleware
module.exports = {
  path: '/api',
  handler: app
}

api/routes/test.ts:
export module test {
// stuff here
}
```

Results in:
```
✖ Nuxt Fatal Error                          │
│                                               │
│   Error: Cannot find module './routes/test
```

Why is this not working? From what I understand ES6 is not working in node, but this should be compiled with `babel-eslint`?

Thanks!

**Comment by francoism90** [comment]
This does work:
`const test = require('./routes/test.ts')`

When taking a look at https://github.com/nuxt-community/typescript-template/blob/master/template/modules/typescript.js, it seems they use:
```
// Add .ts & .tsx extension to Nuxt
this.nuxt.options.extensions.push('ts', 'tsx')
```

Maybe this isn't the solution, but it looks like these extensions are not parsed for me outside nuxt directories?

**Comment by hmsk** [comment]
Thanks for reporting. It'll be great if you provide the full repo to reproduce.
This module is also adding `ts` for the supporting ext, so I may be missing something different.
https://github.com/hmsk/nuxt-ts/blob/master/lib/module.js#L31

**Comment by francoism90** [comment]
@hmsk Turns out this is an issue with Nuxtjs, using `modules/typescript.js` doesn't fix the issue. The reason why I didn't the error is that the server didn't reload.

See [this ticket](https://github.com/nuxt/create-nuxt-app/issues/23#issuecomment-457382121) + given repo, and https://github.com/nuxt/nuxt.js/issues/4852.
